### ISSUE TITLE
Where could I find the source code for the aggregator?

### ISSUE THREAD

**Issue by luanguimaraesla** [mrahbar/k8s-testsuite#2]
I would use the same logic to test inter-cluster communication settings. I found and successfully modified the nptest code, but I did not find the one in the aggregator to perform load tests.

Thank you.

**Comment by luanguimaraesla** [comment]
Also, except by the simple-server repository, I didn't find the other sources used in the test, like vegeta-server implementation you use. Is there any reason not to deploy it, or could you provide these files for inspection and, in my case, improvements and community collaboration?

**Comment by mrahbar** [comment]
Sorry for the inconvenience the source code is also in Github but hidden in another repository: https://github.com/mrahbar/kubespector/tree/master/resources/scaletest . I added the link also to the Readme. Feel free to reopen the issue if something is still missing.
